### ISSUE TITLE
How to get search to only show results from the currently selected namespace/version?

### ISSUE THREAD

**Issue by FaultyFunctions** [palkan/docsify-namespaced#1]
Is there an example of this somewhere? Is this possible?

**Comment by palkan** [comment]
You should use the search plugin's [`pathNamespaces` option](https://docsify.js.org/#/plugins?id=full-text-search). Here is an example: https://github.com/anycable/docs.anycable.io/blob/0341c2919a559552c563f294327fe051667906f9/docs/index.html#L93
