### ISSUE TITLE
Selection doesn't work in _navbar.md

### ISSUE THREAD

**Issue by hamishwillee** [palkan/docsify-namespaced#3]
Just FYI, you can add the selector to your navbar if it is defined in the index.html and it works well.
```
<body>
  <nav>
    <select id="lang-selector" name="lang" class="nav-select">
      <option value="en">English</option>
      <option value="ko">한국어 (Korean)</option>
      <option value="zh">中文 (Chinese)</option>
    </select>
    <select id="ver-selector" name="ver" class="nav-select">
      <option value="main">main</option>
      <option value="v1.15">v1.15</option>
    </select>
  </nav>
...
```

But if you add the same selector to `_navbar.md` the selectors render correctly but changes to the value are not detected.

```
<select id="lang-selector" name="lang">
  <option value="en">English</option>
  <option value="ko">한국어 (Korean)</option>
  <option value="zh">中文 (Chinese)</option>
</select>
<select id="ver-selector" name="ver">
  <option value="main">main</option>
  <option value="v1.15">v1.15</option>
</select>

* Something else
  * [Fred](/en/README.md)
  * [Jim](/zh/README.md)
```

**Comment by palkan** [comment]
Yeah, I think, that's because we look up selectors only on mount: https://github.com/palkan/docsify-namespaced/blob/57105d02b60bc26a22e488f977e16749c70d93fd/src/index.js#L88

But if sidebar is loaded async, we can not find them.

Maybe, adding lookup here could help: https://github.com/palkan/docsify-namespaced/blob/57105d02b60bc26a22e488f977e16749c70d93fd/src/index.js#L124

```js
if (!namespace.selectElement) {
  namespace.selectElement = Docsify.dom.find(namespace.selector);
}

if (!namespace.selectElement) { return; }
```

**Comment by hamishwillee** [comment]
I think so. Thank you. FWIW this plugin is what makes docsify useful to me - as I need both versions and translations.

I don't strictly need this fix, I was just pointing it out to you in case you wanted to address it.

Note, I never got the approach of using a path like lang/version working properly (and I dislike that anyway). But having /version/lang/ and making both of those namespaces mandatory (with default) works a treat. 

FYI only, still playing, but this is what it looks like: https://hamishwillee.github.io/multidocsify_test/#/main/en/ (sidebar works properly on firefox but there is something weird in current chrome (but not previous or future versions)
